# Generated by Django 3.2.9 on 2022-01-29 14:42

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=50, verbose_name='studentID')),
                ('lastName', models.CharField(max_length=50, verbose_name='lastName')),
                ('firstName', models.CharField(max_length=50, verbose_name='firstName')),
                ('middleName', models.CharField(blank=True, max_length=50, verbose_name='middleName')),
                ('course', models.CharField(choices=[('BET', 'Bachelor of Engineering Technology'), ('BSE', 'Bachelor of Science in Engineering'), ('BSIE', 'Bachelor of Science in Industrial Education'), ('BTTE', 'Bachelor of Technical Teacher Education')], default='', max_length=5, verbose_name='course')),
                ('major', models.CharField(choices=[('AET', 'Automotive'), ('CT', 'Civil'), ('COET', 'Computer Engineering Technology'), ('ESET', 'Electronics'), ('EET', 'Electrical'), ('MPET', 'Mechanical'), ('PPET', 'Powerplant'), ('ICT', 'Information Communication Technology'), ('IA', 'Industrial Arts'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], default='', max_length=10, verbose_name='major')),
                ('section', models.CharField(choices=[('S-1A', 'S-1A'), ('NS-1B', 'NS-1B'), ('S-2A', 'S-2A'), ('NS-2B', 'NS-2B'), ('S-3A', 'S-3A'), ('NS-3B', 'NS-3B'), ('S-4A', 'S-4A'), ('NS-4A', 'NS-4A')], default='', max_length=10, verbose_name='section')),
                ('studentNo', models.CharField(max_length=50, verbose_name='studentNo')),
                ('schoolYear', models.CharField(max_length=50, verbose_name='schoolYear')),
                ('addViolation', models.CharField(choices=[('Littering', 'Littering'), ('Loitering', 'Loitering'), ('Vandalism', 'Vandalism'), ('Gambling', 'Gambling'), ('Improper haircut', 'Improper haircut'), ('Improper public behavior', 'Improper public behavior'), ('Improper uniform', 'Improper uniform'), ('Wearing of hats in class', 'Wearing of hats in class'), ('Unauthorized use of water', 'Unauthorized use of water'), ('Use of gadgets during class', 'Use of gadgets during class'), ('Wearing of piercing', 'Wearing of piercing'), ('Cross-dressing', 'Cross-dressing')], default='', max_length=100, verbose_name='addViolation')),
                ('addComSer', models.CharField(choices=[('Summer break volunteer', 'Summer break volunteer'), ('Cafeteria volunteer', 'Cafeteria volunteer'), ('Organizing recyclables', 'Organizing recyclables'), ('Waste segregation', 'Waste segregation'), ('Planting plants', 'Planting plants'), ('Library personnel', 'Library personnel'), ('Garbage collection volunteer', 'Garbage collection volunteer'), ('Community sweeping', 'Community sweeping')], default='', max_length=100, verbose_name='addComSer')),
                ('offenseType', models.CharField(choices=[('First offense', 'First offense'), ('Second offense', 'Second offense'), ('Third Offense', 'Third Offense')], default='', max_length=25, verbose_name='offenseType')),
                ('addComSerTime', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='addComSerTime')),
                ('statusType', models.CharField(choices=[('Ongoing community service', 'Ongoing community service'), ('Completed community service', 'Completed community service')], default='', max_length=50, verbose_name='statusType')),
            ],
        ),
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userType', models.CharField(choices=[('student', 'Student'), ('department', 'OSA-Department')], default='', max_length=20, verbose_name='userType')),
                ('email', models.EmailField(default='', max_length=25, unique=True, verbose_name='email')),
                ('username', models.CharField(default='', max_length=25, unique=True, verbose_name='username')),
                ('is_student', models.BooleanField(default=False)),
                ('is_department', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
