# Generated by Django 3.2.9 on 2021-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0002_auto_20211202_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='major',
            field=models.CharField(choices=[('AET', 'Automotive'), ('CT', 'Civil'), ('COET', 'Computer Engineering Technology'), ('ESET', 'Electronics'), ('EET', 'Electrical'), ('MPET', 'Mechanical'), ('PPET', 'Powerplant'), ('ICT', 'Information Communication Technology'), ('IA', 'Industrial Arts'), ('CPET', 'Computer Programming'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], default='', max_length=10, verbose_name='major'),
        ),
    ]
